openapi: 3.0.3
info:
  title: SnowMirror API
  description: Example Hashicups through Speakeasy
  contact:
    name: ' GuideVision'
    url: 'https://www.snow-mirror.com/doc/RestApiGuide.html'
  version: 0.0.1
servers:
  - url: 'http://localhost:9090'
    description: local
security:
  - basic-authentication: []
externalDocs:
  url: 'https://www.snow-mirror.com/doc/RestApiGuide.html'
  description: The Speakeasy Platform Documentation
tags:
  - name: Synchronization
    description: Synchronization
    externalDocs:
      description: ''
      url: 'https://www.snow-mirror.com/doc/RestApiGuide.html#section-api-sync'
paths:
  /api/v1/synchronization:
    post:
      summary: Create a synchronization
      description: Returns a list of all synchronizations.
      x-speakeasy-entity-operation: Synchronization#create
      operationId: createSynchronization
      requestBody:
        description: A JSON representation of the Api to upsert
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSynchronizationInput'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Synchronization'
          description: OK
      tags:
        - Synchronization
  '/api/v1/synchronization/{id}':
    get:
      summary: Get an synchronizations
      description: Returns a list of all synchronizations.
      x-speakeasy-entity-operation: Synchronization#get
      operationId: getSynchronization
      parameters:
        - description: The ID of the order get.
          in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Synchronization'
          description: OK
      tags:
        - Synchronization
    put:
      summary: Update a synchronization
      description: Returns a list of all synchronizations.
      x-speakeasy-entity-operation: Synchronization#update
      operationId: updateSynchronization
      parameters:
        - description: The id of the sync.
          in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: A JSON representation of the Api to upsert
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSynchronizationInput'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Synchronization'
          description: OK
      tags:
        - Synchronization
    delete:
      summary: Delete a sync
      description: Delete a synchronizations.
      x-speakeasy-entity-operation: Synchronization#delete
      operationId: deleteSynchronization
      parameters:
        - description: The ID of the order to delete.
          in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
      tags:
        - Synchronization
components:
  schemas:
    CreateSynchronizationInput:
      description: An input object to creating a Synchronization
      x-speakeasy-entity: Synchronization
      type: object
      x-stoplight:
        id: d04afae9c8b4d
      properties:
        sync:
          type: object
          properties:
            name:
              type: string
              description: Display name of the synchronization.
              example: incident
            table:
              type: string
              description: Name of the table in ServiceNow.
              example: incident
            view:
              type: string
              description: Name of the view in ServiceNow.
            mirrorTable:
              type: string
              description: Name of the table in mirror database where the data will be migrated.
              example: incident
            columns:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    example: sys_id
            columnsToExclude:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    example: sys_created_by
            allowInheritedColumns:
              type: boolean
              description: 'SnowMirror checks if columns exist in ServiceNow. If this flag is set to true,'
              example: true
            referenceFieldType:
              type: string
              enum:
                - SYS_IDS
                - DISPLAY_VALUES
                - BOTH
              example: BOTH
              description: Defines how to synchronize reference field types.
            autoSchemaUpdate:
              type: boolean
              example: false
              description: |
                Configures how to check for schema changes in ServiceNow.

                Enabled (true) - whenever a synchronization is executed, SnowMirror checks for schema changes in ServiceNow. Automatically adds, updates (data type, max. length of a column) and removes columns. If a new column is added SnowMirror clears the mirror table and downloads all records from scratch.

                Enabled (no truncation) (ENABLED_WITHOUT_TRUNCATION) - the same as Enabled option. It handles new columns differently, though. If a new column is added SnowMirror does not clear the mirror table. Instead, it creates the column and populates it with a default value (which is defined in ServiceNow).
            encodedQuery:
              type: string
            deleteStrategy:
              type: string
              enum:
                - AUDIT
                - TRUNCATE
                - DIFF
                - NONE
              example: AUDIT
            active:
              type: boolean
              description: |-
                true - synchronization is active and can be scheduled to synchronize data from ServiceNow
                false - synchronization is deactivated and cannot be scheduled to synchronize data from ServiceNowNow
              example: true
            runImmediately:
              type: boolean
              description: Determines whether initial synchronization should be done
              example: false
            scheduler:
              type: object
              properties:
                type:
                  type: string
                  description: Specifies when the incremental load synchronization will run
                  enum:
                    - MANUALLY
                    - DAILY
                    - WEEKLY
                    - PERIODICALLY
                    - CRON
                  example: MANUALLY
                beginDate:
                  type: string
                  example: '2014-08-07'
            fullLoadScheduler:
              type: object
              properties:
                executionType:
                  type: string
                  example: CLEAN_AND_SYNCHRONIZE
                type:
                  type: string
                  example: MANUALLY
                beginDate:
                  type: string
                  example: '2014-08-07'
            schedulerPriority:
              type: string
              enum:
                - HIGHEST
                - HIGH
                - NORMAL
                - LOW
                - LOWEST
              example: NORMAL
          required:
            - name
            - mirrorTable
    Synchronization:
      description: Synchronization object
      x-speakeasy-entity: Synchronization
      type: object
      properties:
        id:
          type: integer
          description: fix easyspeak
        sync:
          type: object
          properties:
            id:
              type: integer
              description: Sync ID
              example: 1
            name:
              type: string
              description: Display name of the synchronization.
              example: incident
            table:
              type: string
              description: Name of the table in ServiceNow.
              example: incident
      required:
        - id
        - name
      x-stoplight:
        id: b02cbc78ee913
  securitySchemes:
    basic-authentication:
      type: http
      scheme: basic
