openapi: 3.0.3
info:
  description: Example Hashicups through Speakeasy
  contact:
    name: ' GuideVision'
    url: 'https://www.snow-mirror.com/doc/RestApiGuide.html'
  title: Hashicups
  version: 0.0.1
servers:
  - url: https://example.com
security:
  - APIKey: []
externalDocs:
  url: https://docs.speakeasyapi.dev
  description: The Speakeasy Platform Documentation
tags:
  - name: Synchronization
    description: Synchronization
    externalDocs:
      description: ''
      url: 'https://www.snow-mirror.com/doc/RestApiGuide.html#section-api-sync'  

paths:
  /api/v1/synchronization/{id}:
    get:
      summary: Get an synchronizations
      description: Returns a list of all synchronizations.
      x-speakeasy-entity-operation: Order#get
      operationId: getOrder
      parameters:
        - description: The ID of the order get.
          in: path
          name: id
          x-speakeasy-match: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
          description: OK
      tags:
        - Synchronization
    put:
      summary: Create a synchronization
      description: Returns a list of all synchronizations.
      x-speakeasy-entity-operation: Order#create,update
      operationId: upsertOrder
      parameters:
        - description: The id of the sync.
          in: path
          name: id
          x-speakeasy-match: id
          required: true
          schema:
            type: integer      
      requestBody:
        description: A JSON representation of the Api to upsert
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderInput"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
          description: OK
      tags:
        - Synchronization      
    delete:
      summary: Delete a sync
      description: Delete a synchronizations.
      x-speakeasy-entity-operation: Order#delete
      operationId: deleteOrder
      parameters:
        - description: The ID of the order to delete.
          in: path
          name: id
          x-speakeasy-match: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
      tags:
        - Synchronization
components:
  schemas:
    CreateOrderInput:
      description: An input object to creating an order
      x-speakeasy-entity: Order
      properties:
        name:
          type: string
          description: Product name of the coffee.
        teaser:
          type: string
          description: Fun tagline for the coffee.
        description:
          type: string
          description: Product description of the coffee.
        price:
          type: number
          description: Suggested cost of the coffee.
        image:
          type: string
          description: URI for an image of the coffee.
      required:
        - name
        - teaser
        - price
        - image
      type: object
    Order:
      description: An order helps you make coffee
      x-speakeasy-entity: Order
      properties:
        name:
          type: string
          description: Product name of the coffee.
        id:
          type: integer
          description: Sync ID
        teaser:
          type: string
          description: Fun tagline for the coffee.
        description:
          type: string
          description: Product description of the coffee.
        price:
          type: number
          description: Suggested cost of the coffee.
        image:
          type: string
          description: URI for an image of the coffee.
      required:
        - id
        - name
        - teaser
        - price
        - image
      type: object
  securitySchemes:
    APIKey:
      description: The API Key for the workspace
      in: header
      name: x-api-key
      type: apiKey